CREATE TABLE customer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    create_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);